version: v1

labels:
  - label: area/workflow
    sync: true
    matcher:
      files: ".github/**"

  - label: area/salmon-api-client
    sync: true
    matcher:
      files: "packages/salmon-api-client/**"

  - label: area/salmon-api-wallet
    sync: true
    matcher:
      files: "packages/salmon-api-wallet/**"

  - label: area/module-api
    sync: true
    matcher:
      files: "src/module.api/**"

  - label: area/module-database
    sync: true
    matcher:
      files: "src/module.database/**"

  - label: area/module-defid
    sync: true
    matcher:
      files: "src/module.defid/**"

  - label: area/module-health
    sync: true
    matcher:
      files: "src/module.health/**"

  - label: area/module-indexer
    sync: true
    matcher:
      files: "src/module.indexer/**"

  - label: area/module-model
    sync: true
    matcher:
      files: "src/module.model/**"
