name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.3.1
        with:
          node-version: '15'

      - run: npm ci
      - run: npm run test:ci
      - run: npx codecov

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.3.1
        with:
          node-version: '15'

      - run: npm ci
      - run: npx --no-install ts-standard

  e2e:
    needs: [ lint ]
    name: End-to-end
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - uses: actions/setup-node@v2.3.1
        with:
          node-version: 15

      - run: npm ci
      - run: npm run package

      - name: Setup Playground
        run: docker-compose -f .github/workflows/e2e/docker-compose.yml up -d

      - run: .github/workflows/e2e/wait-for http://localhost:3001/_actuator/probes/liveness -t 120
      - run: .github/workflows/e2e/wait-for http://localhost:3002/_actuator/probes/liveness -t 120
      - run: .github/workflows/e2e/wait-for http://localhost:19551/ping -t 120

      - run: npm run test:e2e
