name: Publish

on:
  release:
    types: [ published, prereleased ]

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - uses: actions/setup-node@v2.2.0
        with:
          node-version: '15'

      - run: |
          npm ci
          npm run build
          npm run package
          cd dist
          zip -r ../bundle.zip .
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      
      - name: Push to s3
        run: |
          aws s3 cp ./bundle.zip s3://salmon-releases/bundle-${GITHUB_REF##*/}.zip
