name: Publish

on:
  release:
    types: [ published, prereleased ]

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: '15'

      - run: |
          npm ci
          npm run build
          npm run package
          cd dist
          zip -r ../bundle.zip .
      
      - name: Upload zip file to release
        uses: svenstaro/upload-release-action@2f88c7710e85b1f8b5f6c3a2fcadaa7f865af713
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./bundle.zip
          asset_name: bundle.zip
          tag: ${{ github.ref }}
          overwrite: true
