name: Labels

on:
  push:
    branches: [ main ]
    paths: [ .github/labels.yml ]

jobs:
  main:
    name: Syncer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.5

      - uses: micnncim/action-label-syncer@3abd5ab72fda571e69fffd97bd4e0033dd5f495c
        with:
          prune: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
